spring.application.name=resumenVentas

server.port=8080

# Flujo de consulta de estado de ingreso con repositorios mock
app.repository.mock-enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/resumen_ventas}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
