spring.application.name=resumenVentas

spring.datasource.url=jdbc:postgresql://localhost:5432/resumen_ventas
spring.datasource.username=postgres
spring.datasource.password=1701
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

server.port=8080

external.gestion-recintos.base-url=http://localhost:8081

spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=always
