/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/recintos/{id}/comision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar comisión del recinto
         * @description Obtiene la comisión configurada para un recinto.
         *
         *     Retorna si está configurada, el tipo (PORCENTAJE o VALOR_FIJO) y el valor asociado.
         */
        get: operations["consultarComision"];
        put?: never;
        /**
         * Registrar comisión del recinto (POST)
         * @description Registra o actualiza la comisión asociada a un recinto.
         *
         *     Tipos de comisión:
         *     - **PORCENTAJE**: Valor decimal (ej: 0.12 = 12%)
         *     - **VALOR_FIJO**: Monto fijo en la moneda local
         */
        post: operations["registrarComision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventos/{id}/configuracion-liquidacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar configuración de liquidación
         * @description Obtiene la configuración de liquidación registrada para un evento.
         *
         *     Si el evento no tiene configuración registrada, retorna un mensaje indicativo.
         */
        get: operations["consultarConfiguracionLiquidacion"];
        put?: never;
        /**
         * Configurar liquidación (POST)
         * @description Configura el tipo de liquidación para un evento usando JSON body.
         *
         *     Modelos de negocio:
         *     - **TARIFA_PLANA**: Enviar `valorComision` con el monto fijo
         *     - **REPARTO_INGRESOS**: Enviar `porcentaje` con la tasa
         */
        post: operations["configurarLiquidacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventos/{id}/calcular-distribucion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calcular distribución del recaudo (GET)
         * @description Método alternativo para navegador. Misma funcionalidad que POST.
         */
        get: operations["calcularDistribucionDesdeNavegador"];
        put?: never;
        /**
         * Calcular distribución del recaudo (POST)
         * @description Calcula la distribución preliminar del recaudo de un evento finalizado.
         *
         *     El cálculo toma en cuenta:
         *     1. Resumen de ventas del evento (Módulo 1)
         *     2. Tipo de recinto y su tasa de comisión
         *     3. Configuración de liquidación (Tarifa Plana o Reparto de Ingresos)
         *     4. Descuentos por tickets cancelados y cortesías
         *
         *     Resultados:
         *     - Total bruto recaudado
         *     - Valor neto preliminar
         *     - Total distribuible
         *     - Estado PRELIMINAR o SIN_RECAUDO
         */
        post: operations["calcularDistribucion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recintos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar recinto por ID
         * @description Obtiene la información de un recinto registrado en el sistema.
         *
         *     El recinto contiene:
         *     - Tipo de recinto (ESTADIO / TEATRO)
         *     - Tasa de comisión asociada
         *     - Estado actual (ACTIVO / INACTIVO)
         */
        get: operations["consultarRecinto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recintos/{id}/comision/configurar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Registrar comisión del recinto (GET)
         * @description Método alternativo para navegador. Requiere recinto existente.
         */
        get: operations["registrarComisionDesdeNavegador"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventos/{id}/resumen-ventas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar resumen de ventas
         * @description Obtiene el resumen consolidado de tickets vendidos para un evento.
         *
         *     Requisitos:
         *     - El evento debe existir en el sistema de gestión de recintos
         *     - El evento debe estar en estado CERRADO
         *     - El servicio externo del Módulo 1 debe estar disponible
         *
         *     La respuesta incluye:
         *     - Total de tickets vendidos
         *     - Total recaudo bruto
         *     - Desglose de tickets por condición de liquidación (VALIDADO, VENDIDO, CANCELADO, CORTESIA)
         *     - Desglose de recaudo por condición de liquidación
         */
        get: operations["consultarResumenVentas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventos/{id}/ingresos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar ingresos de tickets
         * @description Obtiene el resumen de ingresos generados por la venta de tickets de un evento.
         *
         *     La respuesta incluye:
         *     - Total de tickets vendidos, validados, cancelados y cortesías
         *     - Recaudo bruto generado
         *     - Desglose de tickets por estado financiero
         *     - Indicador de inconsistencias si hay tickets sin estado definido
         */
        get: operations["consultarIngresos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventos/{id}/estado-ingreso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar estado de ingreso
         * @description Obtiene el estado de ingreso de todos los tickets vendidos para un evento.
         *
         *     Determina qué tickets fueron utilizados (CHECKED_IN) y cuáles no (NOT_ATTENDED).
         *     Esta información es necesaria para la matriz de liquidación.
         *
         *     Requisitos:
         *     - El evento debe existir en el módulo de control de accesos
         *     - El servicio externo del Módulo 2 debe estar disponible
         */
        get: operations["consultarEstadoIngreso"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventos/{id}/distribucion-recaudo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar distribución del recaudo
         * @description Obtiene la distribución del recaudo liquidada para un evento.
         *
         *     Solo disponible para eventos en estado LIQUIDADO.
         *     Muestra el detalle de montos distribuidos al promotor y comisión de plataforma.
         */
        get: operations["consultarDistribucion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventos/{id}/configuracion-liquidacion/configurar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Configurar liquidación (GET)
         * @description Configura el tipo de liquidación para un evento usando parámetros query.
         *
         *     Método alternativo para navegador. Requiere evento existente y recinto con tipo asignado.
         *
         *     Modelos de negocio:
         *     - **TARIFA_PLANA**: Monto fijo. Enviar `valorComision`.
         *     - **REPARTO_INGRESOS**: Porcentaje. Enviar `porcentaje`.
         */
        get: operations["configurarLiquidacionDesdeNavegador"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Solicitud para registrar la comisión de un recinto */
        RegistrarComisionRecintoRequest: {
            /**
             * @description Tipo de comisión
             * @example PORCENTAJE
             * @enum {string}
             */
            tipoComision: "PORCENTAJE" | "VALOR_FIJO";
            /**
             * @description Valor de la comisión
             * @example 0.12
             */
            valorComision: number;
        };
        /** @description Respuesta del registro de comisión de un recinto */
        RegistrarComisionRecintoResponse: {
            /**
             * Format: int64
             * @description ID de la comisión
             * @example 1
             */
            id?: number;
            /**
             * Format: int64
             * @description ID del recinto
             * @example 1
             */
            recintoId?: number;
            /**
             * @description Tipo de comisión
             * @example PORCENTAJE
             * @enum {string}
             */
            tipoComision?: "PORCENTAJE" | "VALOR_FIJO";
            /**
             * @description Valor de la comisión
             * @example 0.12
             */
            valorComision?: number;
            /**
             * Format: date-time
             * @description Fecha de registro
             * @example 2026-05-07T10:00:00
             */
            fechaRegistro?: string;
            /**
             * @description Mensaje informativo
             * @example Comision registrada exitosamente
             */
            mensaje?: string;
        };
        /** @description Solicitud para configurar el tipo de liquidación de un evento */
        DeterminarTipoLiquidacionRequest: {
            /**
             * @description Tipo de liquidación
             * @example TARIFA_PLANA
             * @enum {string}
             */
            tipoLiquidacion: "TARIFA_PLANA" | "REPARTO_INGRESOS";
            /**
             * @description Valor fijo de comisión (para TARIFA_PLANA)
             * @example 5000
             */
            valorComision?: number;
            /**
             * @description Porcentaje de comisión (para REPARTO_INGRESOS)
             * @example 0.15
             */
            porcentaje?: number;
        };
        /** @description Configuración de liquidación de un evento */
        DeterminarTipoLiquidacionResponse: {
            /**
             * Format: int64
             * @description ID de la configuración
             * @example 1
             */
            id?: number;
            /**
             * Format: int64
             * @description ID del evento
             * @example 1
             */
            eventoId?: number;
            /**
             * @description Tipo de liquidación
             * @example TARIFA_PLANA
             * @enum {string}
             */
            tipoLiquidacion?: "TARIFA_PLANA" | "REPARTO_INGRESOS";
            /**
             * @description Valor fijo de comisión (para tarifa plana)
             * @example 5000
             */
            valorComision?: number;
            /**
             * @description Porcentaje de comisión (para reparto de ingresos)
             * @example 0.15
             */
            porcentaje?: number;
            /**
             * @description Mensaje informativo
             * @example Tipo de liquidacion configurado exitosamente
             */
            mensaje?: string;
        };
        /** @description Resultado del cálculo de distribución del recaudo de un evento */
        CalcularDistribucionResponse: {
            /**
             * Format: int64
             * @description ID del evento
             * @example 1
             */
            eventoId?: number;
            /**
             * @description Nombre del evento
             * @example Concierto Rock 2026
             */
            nombreEvento?: string;
            /**
             * @description Total bruto recaudado
             * @example 62500
             */
            totalBruto?: number;
            /**
             * @description Valor neto preliminar (bruto - cancelados)
             * @example 56000
             */
            totalNetoPreliminar?: number;
            /**
             * @description Total distribuible después de comisiones
             * @example 48200
             */
            totalDistribuible?: number;
            /**
             * @description Comisión de la plataforma
             * @example 6500
             */
            comisionPlataforma?: number;
            /**
             * @description Descuento por tickets cancelados
             * @example 2500
             */
            descuentoCancelados?: number;
            /**
             * @description Descuento por cortesías
             * @example 0
             */
            descuentoCortesia?: number;
            /**
             * @description Estado de la liquidación
             * @example PRELIMINAR
             * @enum {string}
             */
            estado?: "PRELIMINAR" | "SIN_RECAUDO";
            /**
             * Format: date-time
             * @description Fecha del cálculo
             * @example 2026-05-07T10:00:00
             */
            fechaCalculo?: string;
            /**
             * @description Mensaje informativo
             * @example Distribucion del recaudo calculada exitosamente
             */
            mensaje?: string;
        };
        /** @description Información de un recinto */
        ConsultarRecintoResponse: {
            /**
             * Format: int64
             * @description ID del recinto
             * @example 1
             */
            id?: number;
            /**
             * @description Nombre del recinto
             * @example Estadio Nacional
             */
            nombre?: string;
            /**
             * @description Tipo de recinto
             * @example ESTADIO
             * @enum {string}
             */
            tipoRecinto?: "ESTADIO" | "TEATRO";
            /**
             * @description Tasa de comisión asociada al tipo de recinto
             * @example 0.15
             */
            tasaComision?: number;
            /**
             * @description Estado del recinto
             * @example ACTIVO
             * @enum {string}
             */
            estado?: "ACTIVO" | "INACTIVO";
        };
        /** @description Información de la comisión de un recinto */
        ComisionResponse: {
            /**
             * @description Indica si la comisión está configurada
             * @example true
             */
            configurada?: boolean;
            /**
             * @description Mensaje informativo
             * @example Comision configurada
             */
            mensaje?: string;
            /**
             * @description Tipo de comisión
             * @example PORCENTAJE
             * @enum {string}
             */
            tipoComision?: "PORCENTAJE" | "VALOR_FIJO";
            /**
             * @description Valor de la comisión
             * @example 0.12
             */
            valorComision?: number;
        };
        /** @description Resumen consolidado de ventas de un evento */
        ConsultarResumenVentasResponse: {
            /**
             * Format: int64
             * @description ID del evento
             * @example 1
             */
            eventoId?: number;
            /**
             * @description Nombre del evento
             * @example Concierto Rock 2026
             */
            nombreEvento?: string;
            /**
             * @description Estado del evento
             * @example CERRADO
             * @enum {string}
             */
            estadoEvento?: "CERRADO" | "EN_CURSO" | "PROGRAMADO";
            /**
             * Format: int32
             * @description Total de tickets vendidos
             * @example 145
             */
            totalTicketsVendidos?: number;
            /**
             * @description Total recaudo bruto
             * @example 62500
             */
            totalRecaudoBruto?: number;
            /**
             * @description Cantidad de tickets agrupados por condición de liquidación
             * @example {
             *       "VALIDADO": 100,
             *       "VENDIDO": 30,
             *       "CANCELADO": 5,
             *       "CORTESIA": 10
             *     }
             */
            ticketsPorCondicion?: {
                [key: string]: number;
            };
            /**
             * @description Recaudo agrupado por condición de liquidación
             * @example {
             *       "VALIDADO": 50000,
             *       "VENDIDO": 15000,
             *       "CANCELADO": -2500,
             *       "CORTESIA": 0
             *     }
             */
            recaudoPorCondicion?: {
                [key: string]: number;
            };
        };
        /** @description Ingresos generados por la venta de tickets de un evento */
        ConsultarIngresosResponse: {
            /**
             * Format: int64
             * @description ID del evento
             * @example 1
             */
            eventoId?: number;
            /**
             * Format: int32
             * @description Total de tickets vendidos
             * @example 145
             */
            totalTicketsVendidos?: number;
            /**
             * Format: int32
             * @description Total de tickets validados (check-in)
             * @example 100
             */
            totalTicketsValidados?: number;
            /**
             * Format: int32
             * @description Total de tickets cancelados
             * @example 5
             */
            totalTicketsCancelados?: number;
            /**
             * Format: int32
             * @description Total de cortesías
             * @example 10
             */
            totalCortesias?: number;
            /**
             * Format: int32
             * @description Total de tickets no asistieron
             * @example 30
             */
            totalNoAsistieron?: number;
            /**
             * @description Total recaudo bruto
             * @example 62500
             */
            totalRecaudoBruto?: number;
            /**
             * @description Tickets agrupados por estado financiero
             * @example {
             *       "VALIDADO": 100,
             *       "VENDIDO": 30,
             *       "CANCELADO": 5,
             *       "CORTESIA": 10
             *     }
             */
            ticketsPorEstado?: {
                [key: string]: number;
            };
            /**
             * @description Indica si hay tickets sin estado definido
             * @example false
             */
            hasInconsistencies?: boolean;
        };
        /** @description Estado de ingreso de tickets de un evento */
        ConsultarEstadoIngresoResponse: {
            /**
             * Format: int64
             * @description ID del evento
             * @example 1
             */
            eventoId?: number;
            /**
             * @description Nombre del evento
             * @example Concierto Rock 2026
             */
            nombreEvento?: string;
            /** @description Lista de tickets con su estado de ingreso */
            tickets?: components["schemas"]["TicketEstadoIngreso"][];
            /**
             * Format: int32
             * @description Total de tickets
             * @example 130
             */
            totalTickets?: number;
            /**
             * Format: int32
             * @description Total de tickets con check-in realizado
             * @example 100
             */
            totalCheckeados?: number;
            /**
             * Format: int32
             * @description Total de tickets sin check-in
             * @example 30
             */
            totalNoAsistieron?: number;
        };
        /** @description Estado de ingreso de un ticket individual */
        TicketEstadoIngreso: {
            /**
             * Format: int64
             * @description ID del ticket
             * @example 1
             */
            idTicket?: number;
            /**
             * @description Código del ticket
             * @example TKT-1
             */
            codigoTicket?: string;
            /**
             * @description Estado de ingreso
             * @example CHECKED_IN
             * @enum {string}
             */
            estadoIngreso?: "CHECKED_IN" | "NOT_ATTENDED";
            /**
             * @description Tipo de acceso
             * @example INGRESO
             * @enum {string}
             */
            tipoAcceso?: "INGRESO" | "REINGRESO";
        };
        /** @description Distribución del recaudo liquidada para un evento */
        ConsultarDistribucionResponse: {
            /**
             * Format: int64
             * @description ID del evento
             * @example 1
             */
            eventoId?: number;
            /**
             * @description Nombre del evento
             * @example Concierto Rock 2026
             */
            nombreEvento?: string;
            /**
             * @description Total bruto recaudado
             * @example 62500
             */
            totalBruto?: number;
            /**
             * @description Total pago al promotor
             * @example 48200
             */
            totalPagoPromotor?: number;
            /**
             * @description Total comisión de plataforma
             * @example 6500
             */
            totalComisionPlataforma?: number;
            /**
             * @description Total distribuible
             * @example 48200
             */
            totalDistribuible?: number;
            /**
             * @description Estado de la liquidación
             * @example LIQUIDADO
             * @enum {string}
             */
            estado?: "PRELIMINAR" | "LIQUIDADO" | "SIN_RECAUDO";
            /**
             * Format: date-time
             * @description Fecha del cálculo
             * @example 2026-05-07T10:00:00
             */
            fechaCalculo?: string;
            /**
             * Format: date-time
             * @description Fecha de liquidación
             * @example 2026-05-07T12:00:00
             */
            fechaLiquidacion?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    consultarComision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ID del recinto
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comisión consultada exitosamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "configurada": true,
                     *       "mensaje": "Comision configurada",
                     *       "tipoComision": "PORCENTAJE",
                     *       "valorComision": 0.12
                     *     }
                     */
                    "*/*": components["schemas"]["ComisionResponse"];
                };
            };
            /** @description Recinto no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "RECINTO_NOT_FOUND",
                     *       "message": "El recinto no se encuentra registrado",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
            /** @description Servicio externo no disponible */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ComisionResponse"];
                };
            };
        };
    };
    registrarComision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ID del recinto
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarComisionRecintoRequest"];
            };
        };
        responses: {
            /** @description Comisión registrada exitosamente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "recintoId": 1,
                     *       "tipoComision": "PORCENTAJE",
                     *       "valorComision": 0.12,
                     *       "fechaRegistro": "2026-05-07T10:00:00",
                     *       "mensaje": "Comision registrada exitosamente"
                     *     }
                     */
                    "*/*": components["schemas"]["RegistrarComisionRecintoResponse"];
                };
            };
            /** @description Solicitud inválida (validación de campos) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INVALID_REQUEST",
                     *       "message": "El valor de comision debe ser cero o positivo",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
            /** @description Recinto no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegistrarComisionRecintoResponse"];
                };
            };
            /** @description Servicio externo no disponible */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegistrarComisionRecintoResponse"];
                };
            };
        };
    };
    consultarConfiguracionLiquidacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ID del evento
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuración encontrada o mensaje informativo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "eventoId": 1,
                     *       "tipoLiquidacion": "TARIFA_PLANA",
                     *       "valorComision": 5000,
                     *       "porcentaje": 0,
                     *       "mensaje": "Tipo de liquidacion configurado exitosamente"
                     *     }
                     */
                    "*/*": components["schemas"]["DeterminarTipoLiquidacionResponse"];
                };
            };
            /** @description Evento no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EVENT_NOT_FOUND",
                     *       "message": "El evento no se encuentra registrado",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
        };
    };
    configurarLiquidacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ID del evento
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeterminarTipoLiquidacionRequest"];
            };
        };
        responses: {
            /** @description Configuración creada exitosamente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "eventoId": 1,
                     *       "tipoLiquidacion": "TARIFA_PLANA",
                     *       "valorComision": 5000,
                     *       "porcentaje": null,
                     *       "mensaje": "Tipo de liquidacion configurado exitosamente"
                     *     }
                     */
                    "*/*": components["schemas"]["DeterminarTipoLiquidacionResponse"];
                };
            };
            /** @description Solicitud inválida (validación de campos) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeterminarTipoLiquidacionResponse"];
                };
            };
            /** @description Evento no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeterminarTipoLiquidacionResponse"];
                };
            };
            /** @description Servicio externo no disponible */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeterminarTipoLiquidacionResponse"];
                };
            };
        };
    };
    calcularDistribucionDesdeNavegador: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ID del evento
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distribución calculada exitosamente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CalcularDistribucionResponse"];
                };
            };
        };
    };
    calcularDistribucion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ID del evento
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distribución calculada exitosamente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "eventoId": 1,
                     *       "nombreEvento": "Concierto Rock 2026",
                     *       "totalBruto": 62500,
                     *       "totalNetoPreliminar": 56000,
                     *       "totalDistribuible": 48200,
                     *       "comisionPlataforma": 6500,
                     *       "descuentoCancelados": 2500,
                     *       "descuentoCortesia": 0,
                     *       "estado": "PRELIMINAR",
                     *       "fechaCalculo": "2026-05-07T10:00:00",
                     *       "mensaje": "Distribucion del recaudo calculada exitosamente"
                     *     }
                     */
                    "*/*": components["schemas"]["CalcularDistribucionResponse"];
                };
            };
            /** @description Evento o recinto no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CalcularDistribucionResponse"];
                };
            };
            /** @description Evento no cerrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CalcularDistribucionResponse"];
                };
            };
            /** @description Servicio externo no disponible */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CalcularDistribucionResponse"];
                };
            };
        };
    };
    consultarRecinto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ID del recinto
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recinto encontrado exitosamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "nombre": "Estadio Nacional",
                     *       "tipoRecinto": "ESTADIO",
                     *       "tasaComision": 0.15,
                     *       "estado": "ACTIVO"
                     *     }
                     */
                    "*/*": components["schemas"]["ConsultarRecintoResponse"];
                };
            };
            /** @description Recinto no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "RECINTO_NOT_FOUND",
                     *       "message": "El recinto no se encuentra registrado",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
            /** @description Servicio externo no disponible */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EXTERNAL_SERVICE_UNAVAILABLE",
                     *       "message": "No fue posible obtener la información de ventas",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
        };
    };
    registrarComisionDesdeNavegador: {
        parameters: {
            query: {
                /**
                 * @description Tipo de comisión (PORCENTAJE o VALOR_FIJO)
                 * @example PORCENTAJE
                 */
                tipoComision: "PORCENTAJE" | "VALOR_FIJO";
                /**
                 * @description Valor de la comisión
                 * @example 0.12
                 */
                valorComision: number;
            };
            header?: never;
            path: {
                /**
                 * @description ID del recinto
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comisión registrada exitosamente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegistrarComisionRecintoResponse"];
                };
            };
            /** @description Recinto no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegistrarComisionRecintoResponse"];
                };
            };
            /** @description Servicio externo no disponible */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegistrarComisionRecintoResponse"];
                };
            };
        };
    };
    consultarResumenVentas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ID del evento
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumen de ventas obtenido exitosamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "eventoId": 1,
                     *       "nombreEvento": "Concierto Rock 2026",
                     *       "estadoEvento": "CERRADO",
                     *       "totalTicketsVendidos": 145,
                     *       "totalRecaudoBruto": 62500,
                     *       "ticketsPorCondicion": {
                     *         "VALIDADO": 100,
                     *         "VENDIDO": 30,
                     *         "CANCELADO": 5,
                     *         "CORTESIA": 10
                     *       },
                     *       "recaudoPorCondicion": {
                     *         "VALIDADO": 50000,
                     *         "VENDIDO": 15000,
                     *         "CANCELADO": -2500,
                     *         "CORTESIA": 0
                     *       }
                     *     }
                     */
                    "*/*": components["schemas"]["ConsultarResumenVentasResponse"];
                };
            };
            /** @description Evento no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EVENT_NOT_FOUND",
                     *       "message": "El evento no se encuentra registrado",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
            /** @description Evento no está cerrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EVENT_NOT_CLOSED",
                     *       "message": "El evento aún no ha sido cerrado. Estado actual: EN_CURSO",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
            /** @description Servicio externo no disponible */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EXTERNAL_SERVICE_UNAVAILABLE",
                     *       "message": "No fue posible obtener la información de ventas",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
        };
    };
    consultarIngresos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ID del evento
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingresos obtenidos exitosamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "eventoId": 1,
                     *       "totalTicketsVendidos": 145,
                     *       "totalTicketsValidados": 100,
                     *       "totalTicketsCancelados": 5,
                     *       "totalCortesias": 10,
                     *       "totalNoAsistieron": 30,
                     *       "totalRecaudoBruto": 62500,
                     *       "ticketsPorEstado": {
                     *         "VALIDADO": 100,
                     *         "VENDIDO": 30,
                     *         "CANCELADO": 5,
                     *         "CORTESIA": 10
                     *       },
                     *       "hasInconsistencies": false
                     *     }
                     */
                    "*/*": components["schemas"]["ConsultarIngresosResponse"];
                };
            };
            /** @description Evento no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EVENT_NOT_FOUND",
                     *       "message": "El evento no se encuentra registrado",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
            /** @description Servicio externo no disponible */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EXTERNAL_SERVICE_UNAVAILABLE",
                     *       "message": "No fue posible obtener la información de ventas",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
        };
    };
    consultarEstadoIngreso: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ID del evento
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado de ingreso obtenido exitosamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "eventoId": 1,
                     *       "nombreEvento": "Concierto Rock 2026",
                     *       "tickets": [
                     *         {
                     *           "idTicket": 1,
                     *           "codigoTicket": "TKT-1",
                     *           "estadoIngreso": "CHECKED_IN",
                     *           "tipoAcceso": "INGRESO"
                     *         },
                     *         {
                     *           "idTicket": 2,
                     *           "codigoTicket": "TKT-2",
                     *           "estadoIngreso": "NOT_ATTENDED",
                     *           "tipoAcceso": null
                     *         }
                     *       ],
                     *       "totalTickets": 130,
                     *       "totalCheckeados": 100,
                     *       "totalNoAsistieron": 30
                     *     }
                     */
                    "*/*": components["schemas"]["ConsultarEstadoIngresoResponse"];
                };
            };
            /** @description Evento no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EVENT_NOT_FOUND",
                     *       "message": "No se encontraron registros de ingreso para el evento",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
            /** @description Servicio externo no disponible */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EXTERNAL_SERVICE_UNAVAILABLE",
                     *       "message": "No fue posible obtener la información de ventas",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
        };
    };
    consultarDistribucion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ID del evento
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distribución encontrada exitosamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "eventoId": 1,
                     *       "nombreEvento": "Concierto Rock 2026",
                     *       "totalBruto": 62500,
                     *       "totalPagoPromotor": 48200,
                     *       "totalComisionPlataforma": 6500,
                     *       "totalDistribuible": 48200,
                     *       "estado": "LIQUIDADO",
                     *       "fechaCalculo": "2026-05-07T10:00:00",
                     *       "fechaLiquidacion": "2026-05-07T12:00:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ConsultarDistribucionResponse"];
                };
            };
            /** @description Distribución no encontrada o evento no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "DISTRIBUTION_NOT_FOUND",
                     *       "message": "No se encontro la distribucion del recaudo para el evento",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
            /** @description Evento no liquidado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "DISTRIBUTION_NOT_LIQUIDATED",
                     *       "message": "El evento aun no tiene liquidacion disponible",
                     *       "timestamp": "2026-05-07T10:00:00"
                     *     }
                     */
                    "*/*": unknown;
                };
            };
        };
    };
    configurarLiquidacionDesdeNavegador: {
        parameters: {
            query: {
                /**
                 * @description Tipo de liquidación (TARIFA_PLANA o REPARTO_INGRESOS)
                 * @example REPARTO_INGRESOS
                 */
                tipoLiquidacion: "TARIFA_PLANA" | "REPARTO_INGRESOS";
                /**
                 * @description Valor fijo de comisión (para TARIFA_PLANA)
                 * @example 5000
                 */
                valorComision?: number;
                /**
                 * @description Porcentaje de comisión (para REPARTO_INGRESOS)
                 * @example 0.15
                 */
                porcentaje?: number;
            };
            header?: never;
            path: {
                /**
                 * @description ID del evento
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuración creada exitosamente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "eventoId": 1,
                     *       "tipoLiquidacion": "REPARTO_INGRESOS",
                     *       "valorComision": null,
                     *       "porcentaje": 0.15,
                     *       "mensaje": "Tipo de liquidacion configurado exitosamente"
                     *     }
                     */
                    "*/*": components["schemas"]["DeterminarTipoLiquidacionResponse"];
                };
            };
            /** @description Evento no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeterminarTipoLiquidacionResponse"];
                };
            };
            /** @description Servicio externo no disponible */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeterminarTipoLiquidacionResponse"];
                };
            };
        };
    };
}
