spring:
  application:
    name: liquidation-events-services
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticket_events}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

server:
  port: ${PORT:8080}

app:
  repository:
    mock-enabled: ${MOCK_REPOSITORY_ENABLED:false}
